<?php $this->layout('layout::default', ['title' => 'Home']) ?>

<div class="jumbotron">
    <h1>Welcome to <span class="zf-green">Mezzio</span></h1>
    <p>
        Congratulations! You have successfully installed the
        <a href="https://github.com/mezzio/mezzio-skeleton" target="_blank">Mezzio skeleton
            application</a>.
        This skeleton can serve as a simple starting point for you to begin building your application.
    </p>
    <p>
        Expressive builds on laminas-stratigility to provide a minimalist PSR-7 middleware framework for PHP.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>
            <a href="#">
                <i class="fa fa-bolt"></i> Database Demo
            </a>
        </h2>
        <ul>
            <?php foreach ($pdoDemo as $demo): ?>
                <li><?= $demo ?></li>
            <?php endforeach; ?>
        </ul>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="#">
                <i class="fa fa-exchange-alt"></i> IP Address & UA
            </a>
        </h2>
        <ul>
            <li><strong>IP Remote:</strong> <?= $ipRemote ?></li>
            <li><strong>IP via Proxy:</strong> <?= $ipViaProxy ?></li>
            <li><strong>UserAgent:</strong> <?= $userAgent ?></li>
        </ul>
    </div>

    <div class="col-md-4">
        <h2>
            <a href="https://github.com/laminas/laminas-stratigility" target="_blank">
                <i class="fa fa-dot-circle"></i> Middleware
            </a>
        </h2>
        <p>
            Middleware is code that exists between the request and response, and which can take the incoming
            request, perform actions based on it, and either complete the response or pass delegation on to the
            next middleware in the queue. Your application is easily extended with custom middleware created by
            yourself or <a href="https://packagist.org/search/?q=middleware" target="_blank">others</a>.
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2><i class="fa fa-cube"></i> Containers</h2>
        <p>
            Expressive promotes and advocates the usage of Dependency Injection/Inversion of Control containers
            when writing your applications. Expressive supports multiple containers which typehints against
            <a href="https://github.com/php-fig/container" target="_blank">PSR Container</a>.
        </p>
        <?php if (isset($containerName)) : ?>
            <p>
                <a href="<?= $this->e($containerDocs) ?>" target="_blank">
                    Get started with <?= $this->e($containerName) ?>.
                </a>
            </p>
        <?php endif; ?>
    </div>

    <div class="col-md-4">
        <h2><i class="fa fa-plane"></i> Routers</h2>
        <p>
            One fundamental feature of Mezzio is that it provides mechanisms for implementing dynamic
            routing, a feature required in most modern web applications. Expressive ships with multiple adapters.
        </p>
        <?php if (isset($routerName)) : ?>
            <p>
                <a href="<?= $this->e($routerDocs) ?>" target="_blank">
                    Get started with <?= $this->e($routerName) ?>.
                </a>
            </p>
        <?php endif; ?>
    </div>

    <div class="col-md-4">
        <h2><i class="fa fa-edit"></i> Templating</h2>
        <p>
            By default, no middleware in Expressive is templated. We do not even provide a default templating
            engine, as the choice of templating engine is often very specific to the project and/or organization.
            However, Expressive does provide abstraction for templating, which allows you to write middleware that
            is engine-agnostic.
        </p>
        <?php if (isset($templateName)) : ?>
            <p>
                <a href="<?= $this->e($templateDocs) ?>" target="_blank">
                    Get started with <?= $this->e($templateName) ?>.
                </a>
            </p>
        <?php endif; ?>
    </div>
</div>
